### Model Config
defaults:
  - mvsplat/encoder: costvolume
  - mvsplat/decoder: splatting_cuda

### INPUT
expname : test
rootdir : data/ibrnet/train
distributed : False
enable_tensorboard : True
enable_visdom : False
seed : 3407
pretrained : False
local_rank : 0

## dataset
train_dataset : waymo
train_scenes : ['019']
dataset_weights : [1]
eval_dataset : waymo
eval_scenes : ['019']

num_source_views : 4
workers : 16

selection_rule : pose
random_crop : False
outlier_ratio : 0.2
noise_level : 0.15
testskip : 8

no_load_opt: True
no_load_scheduler: True

### TRAINING
n_iters: 3000
use_pred_pose: False
use_kl_depth_loss: False

optimizer:
  lr: 5e-5
  warm_up_steps: 500

### CONSOLE AND TENSORBOARD
n_validation : 1000
n_tensorboard : 2
n_checkpoint : 500
visdom_port : 9000

### evaluation options
llffhold : 8