### Model Config
defaults:
  - mvsplat/encoder: costvolume
  - mvsplat/decoder: splatting_cuda

### INPUT
expname : test
rootdir : data/ibrnet/train
distributed : False
enable_tensorboard : True
enable_visdom : False
seed : 3407
pretrained : False
local_rank : 0

## dataset
train_dataset : waymo
train_scenes : ['019']
dataset_weights : [1]
eval_dataset : waymo
eval_scenes : ['019']

num_source_views : 4
workers : 8

selection_rule : pose
random_crop : False
outlier_ratio : 0.2
noise_level : 0.15
testskip : 8

no_load_opt: True
no_load_scheduler: True

### TRAINING
n_iters: 100000
use_pred_pose: False
use_kl_depth_loss: False
use_aux_loss: False
aux_cof: 1.0

optimizer:
  lr: 5e-5
  warm_up_steps: 500

### CONSOLE AND TENSORBOARD
n_validation : 1000
n_tensorboard : 2
n_checkpoint : 10000
visdom_port : 9000

### evaluation options
llffhold : 8


N_rand : 500
lrate_feature : 0.001
lrate_mlp : 0.0005
lrate_pose : 0.00002
lrate_decay_factor : 0.5
lrate_decay_steps : 2000
lrate_decay_pose_steps : 2000
coarse_only : True
rectify_inplane_rotation: False
coarse_feat_dim : 64 # original:32
fine_feat_dim : 32 # original:128
anti_alias_pooling : 
render_stride : 2
chunk_size : 2000
N_importance : 0 #64
N_samples : 64
inv_uniform : True
white_bkgd : False
sample_mode : uniform
center_ratio : 0.8
feat_loss_scale : 1e1